# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Configuration                       +
# project    nord-hyper                                    +
# repository https://github.com/arcticicestudio/nord-hyper +
# author     Arctic Ice Studio                             +
# email      development@arcticicestudio.com               +
# copyright  Copyright (c) 2017                            +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI Documentation
#   (https://docs.travis-ci.com)
language: node_js
node_js:
  - "6"
  - "4"
cache: yarn
before_script:
  - yarn global add gulp
  - yarn install
script: gulp --harmony lint
